### ISSUE TITLE
Centos 弄好了

### ISSUE THREAD

**Issue by TeQuieroS** [JS-banana/notify-server#45]
但是只有早安可以用 晚安和午安不行
/home/opc/zaoan/src/libs/LoveMsg/goodAfternoon.ts:17
${res.map(n => `『${n.title}』${n.content}`).join('\n\n')}`
      ^

TypeError: Cannot read properties of undefined (reading 'map')
    at goodAfternoon (/home/opc/zaoan/src/libs/LoveMsg/goodAfternoon.ts:17:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

/home/opc/zaoan/src/libs/LoveMsg/goodEvening.ts:90
『${res.title}』
        ^

TypeError: Cannot read properties of undefined (reading 'title')
    at getStory (/home/opc/zaoan/src/libs/LoveMsg/goodEvening.ts:90:8)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at goodEvening (/home/opc/zaoan/src/libs/LoveMsg/goodEvening.ts:100:3)

**Comment by JS-banana** [comment]
接口返回值有问题，map循环报错了，看下天行接口看下是否申请，对应接口需要申请

**Comment by TeQuieroS** [comment]
可以了，期待大佬完成整个项目

**Comment by JS-banana** [comment]
> 可以了，期待大佬完成整个项目

哈哈哈，尽量做到全面通用点吧，全部都搞精力也不够😂，目前确实又出现了一些要优化的地方倒是😟
